#11: create ETL process for cucumber files
RESOStandards/reso-certification-etl pull request #12
Opened 2022-10-19 13:06 UTC by mohit-s96

This is still a WIP as I need some clarity on some things. The method for filtering out failed steps and parsing the `error_message` and the `error.log` message is working as expected. I need more info on what information would be passed to the ETL function and in what order.

2023-03-07 17:33 UTC, darnjo requested changes
Looks good so far. 

Some things that are needed:
* Add Mocha test for error ETL process testing a passed-only file with the cucumber parser (should return nothing), an error-only file (should return only that error), and a file that has a passed and failed step (should return only the error and ignore passed).
* For error logs, the input will be multi line (each line separated with new lines). When this happens, the ETL process should have an array of errors, one for each message.

2023-03-21 17:27 UTC, darnjo requested changes
Need to change lib/reference-metadata/dd-1.7.json back to lib/references/dd-1.7/metadata-report.js

2023-03-30 15:36 UTC, darnjo requested changes

2023-03-30 15:36 UTC, darnjo commented on lib/common.js
> +    field => field.fieldName === fieldName && field.resourceName === resourceName
Optional for `field?.fieldName` and `field?.resourceName`.

2023-03-30 15:36 UTC, darnjo commented on test/etl.js
> +          'Request to https://retsapi.raprets.com/2/bari/RESO/OData/Offices?$filter=ModificationTimestamp lt 2022-12-19T22:23:08.573Z&$orderby=ModificationTimestamp desc&$top=100 failed! No response
In general, we should try and remove the provider's API info. We can use something like test.reso.org.

2023-03-30 15:43 UTC, darnjo approved these changes

2023-03-30 15:44 UTC, merged

2023-11-21 07:50 UTC, mohit-s96 commented
A commit in this branch is being used on qa atm (00be7f490e06fb61bf0904703ed0791b59b736f0). We can delete this and move on to use the main branch once the frontend can support the new bins changes. cc:@darnjo